{% set name = "dpm360-lightsaber" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dpm360-lightsaber-{{ version }}.tar.gz
  sha256: 3b286d7407503195b73a792dc74a7f567d2996312a96fc498c6855bad1e6d873

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - mlflow >=1.2.0
    - pytorch-lightning >=1.*
    - scikit-learn >=1.*
    - pandas >=1.2
    - tabulate
    - toolz
    - python >={{ python_min }}

test:
  imports:
    - lightsaber
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/IBM/DPM360
  doc_url: https://ibm.github.io/DPM360/Lightsaber/
  summary: Package to handle model training for dpm tasks
  license: Apache-2.0
  license_file: LICENSE.txt


extra:
  recipe-maintainers:
    - pchakraborty1
    - akoseki2
    - rachita-c
